# Generated by Django 5.1.6 on 2025-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='package',
            new_name='annual_salary',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='city',
            new_name='current_company_designation',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='company',
            new_name='current_company_name',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='education',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='date_of_application',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='doctorate_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='doctorate_graduation_year',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='doctorate_specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='doctorate_university_institute_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='email_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='home_town_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('Product Manager', 'Product Manager'), ('DevOps Engineer', 'DevOps Engineer'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('UX Designer', 'UX Designer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='key_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='marital_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='notice_period_availability_to_join',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pg_graduation_year',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pg_specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pg_university_institute_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='post_graduation_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='resume_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='total_experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ug_graduation_year',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ug_specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='ug_university_institute_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='under_graduation_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='work_permit_for_usa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
