# Generated by Django 5.1.6 on 2025-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0002_rename_package_exceldata_annual_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='current_company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='current_location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='date_of_application',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('Product Manager', 'Product Manager'), ('DevOps Engineer', 'DevOps Engineer'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('UX Designer', 'UX Designer'), ('Front end Developer', 'Front end Developer'), ('Back end Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Other', 'Other')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='total_experience',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='exceldata',
            index=models.Index(fields=['job_title', 'current_location'], name='aap_api_exc_job_tit_de3dee_idx'),
        ),
        migrations.AddIndex(
            model_name='exceldata',
            index=models.Index(fields=['name', 'current_company_name'], name='aap_api_exc_name_65453a_idx'),
        ),
        migrations.AddIndex(
            model_name='exceldata',
            index=models.Index(fields=['date_of_application', 'total_experience'], name='aap_api_exc_date_of_b2e9b3_idx'),
        ),
    ]
