# Generated by Django 5.1.6 on 2025-02-24 05:54

import aap_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0003_alter_exceldata_current_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='file',
            field=models.FileField(upload_to=aap_api.models.UploadedExcel.upload_path),
        ),
    ]
