# Generated by Django 5.1.6 on 2025-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0004_alter_uploadedexcel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('filters', models.JSONField()),
                ('record_count', models.IntegerField()),
            ],
        ),
    ]
