# Generated by Django 5.1.6 on 2025-03-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_api', '0006_alter_exceldata_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='zip_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
